services:
  - type: web
    name: asset-survey-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true